# Generated by Django 3.0.8 on 2020-09-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='postalcode',
        ),
    ]
