# Generated by Django 3.0.8 on 2020-09-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='postalcode',
        ),
    ]
