# Generated by Django 3.0.8 on 2020-09-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20200908_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills2',
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_app.Profile'),
            preserve_default=False,
        ),
    ]
