# Generated by Django 3.0.8 on 2020-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20200908_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postalcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='core_app.Skill'),
        ),
    ]
